/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Accounts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Accounts__factory>;
    getContractFactory(
      name: "Documents",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Documents__factory>;
    getContractFactory(
      name: "Services",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Services__factory>;
    getContractFactory(
      name: "Utils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Utils__factory>;

    getContractAt(
      name: "Accounts",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Accounts>;
    getContractAt(
      name: "Documents",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Documents>;
    getContractAt(
      name: "Services",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Services>;
    getContractAt(
      name: "Utils",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Utils>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
